-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. APP USERS (Linked to auth.users usually, but standalone for now)
CREATE TYPE user_role AS ENUM ('SuperAdmin', 'Vendedor', 'Cliente');

CREATE TABLE IF NOT EXISTS app_users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    auth_uid UUID REFERENCES auth.users(id),
    name TEXT NOT NULL,
    cedula TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    role user_role DEFAULT 'Cliente',
    balance_bigint BIGINT DEFAULT 0,
    currency TEXT DEFAULT 'CRC',
    status TEXT DEFAULT 'Active',
    pin_hash TEXT,
    failed_attempts INTEGER DEFAULT 0,
    locked_until TIMESTAMPTZ,
    issuer_id UUID, -- For hierarchy (who created this user)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. BETS
CREATE TABLE IF NOT EXISTS bets (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ticket_code TEXT NOT NULL UNIQUE,
    user_id UUID REFERENCES app_users(id),
    vendor_id UUID REFERENCES app_users(id),
    draw_id UUID, -- Optional link to a draw table if normalized
    amount_bigint BIGINT NOT NULL,
    numbers TEXT NOT NULL, -- "90", "90,12,34"
    mode TEXT NOT NULL, -- "TIEMPOS", "REVENTADOS"
    status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. LEDGER TRANSACTIONS
CREATE TABLE IF NOT EXISTS ledger_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ticket_code TEXT,
    user_id UUID REFERENCES app_users(id),
    amount_bigint BIGINT NOT NULL,
    balance_before BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    type TEXT NOT NULL,
    reference_id TEXT,
    meta JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. AUDIT TRAIL
CREATE TABLE IF NOT EXISTS audit_trail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    actor_id UUID, -- Can be null for system events
    actor_role TEXT,
    actor_name TEXT,
    ip_address TEXT,
    device_fingerprint TEXT,
    type TEXT NOT NULL,
    action TEXT NOT NULL,
    severity TEXT NOT NULL,
    target_resource TEXT,
    metadata JSONB,
    hash TEXT,
    previous_hash TEXT
);

-- 5. DRAW RESULTS
CREATE TABLE IF NOT EXISTS draw_results (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date DATE NOT NULL,
    "drawTime" TEXT NOT NULL, -- Quoted because camelCase in code
    "winningNumber" TEXT NOT NULL,
    "isReventado" BOOLEAN DEFAULT FALSE,
    "reventadoNumber" TEXT,
    status TEXT DEFAULT 'CLOSED',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, "drawTime")
);

-- 6. SYSTEM SETTINGS
CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    "group" TEXT DEFAULT 'CORE',
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    updated_by UUID
);

-- 7. RISK LIMITS
CREATE TABLE IF NOT EXISTS risk_limits (
    draw_type TEXT NOT NULL,
    number TEXT NOT NULL,
    max_amount BIGINT NOT NULL,
    PRIMARY KEY (draw_type, number)
);

-- Enable RLS (Row Level Security) - Basic open policies for now to ensure app works, lock down later
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_trail ENABLE ROW LEVEL SECURITY;
ALTER TABLE draw_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE risk_limits ENABLE ROW LEVEL SECURITY;

-- Policies (Permissive for initial setup/admin usage)
CREATE POLICY "Allow public read access" ON app_users FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON bets FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON ledger_transactions FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON audit_trail FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON draw_results FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON system_settings FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON risk_limits FOR SELECT USING (true);

CREATE POLICY "Allow authenticated update" ON app_users FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated insert" ON bets FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated insert" ON ledger_transactions FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated insert" ON audit_trail FOR INSERT WITH CHECK (true); -- Audit needs to be writable broadly often
